name: 'Deploy Artifact'
description: 'Builds and deploys an artifact to Google Cloud Run'
inputs:
  GCP_CREDENTIALS:
    description: 'Google Cloud credentials JSON'
    required: true
  GOOGLE_PROJECT:
    description: 'Google Cloud project ID'
    required: true
  CR_URL:
    description: 'Container Registry URL'
    required: true
  ARTIFACT_FOLDER:
    description: 'Artifact folder in the container registry'
    required: true
  IMAGE_NAME:
    description: 'Image name'
    required: true
  TARGET_SERVICE:
    description: 'Target service for deployment'
    required: true
  PORT:
    description: 'Port number'
    required: true
  REGION:
    description: 'Google Cloud region'
    required: true
  SA_MAIL:
    description: 'Service account email'
    required: true

runs:
  using: "composite"
  steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.GCP_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.GOOGLE_PROJECT }}
        export_default_credentials: true

    - name: build and push image to artifact
      run: |
        gcloud auth configure-docker ${{ inputs.CR_URL }}
        docker build -t ${{ inputs.CR_URL }}/${{ inputs.GOOGLE_PROJECT }}/${{ inputs.ARTIFACT_FOLDER }}/${{ inputs.IMAGE_NAME }}:${{ github.sha }} .
        docker push ${{ inputs.CR_URL }}/${{ inputs.GOOGLE_PROJECT }}/${{ inputs.ARTIFACT_FOLDER }}/${{ inputs.IMAGE_NAME }}:${{ github.sha }}
      env:
        GOOGLE_PROJECT: ${{ inputs.GOOGLE_PROJECT }}
        CR_URL: ${{ inputs.CR_URL }}

    - name: deploy
      run: |
        gcloud run deploy ${{ inputs.TARGET_SERVICE }} --image ${{ inputs.CR_URL }}/${{ inputs.GOOGLE_PROJECT }}/${{ inputs.ARTIFACT_FOLDER }}/${{ inputs.IMAGE_NAME }}:${{ github.sha }} --port=${{ inputs.PORT }} --region '${{ inputs.REGION }}' --service-account '${{ inputs.SA_MAIL }}'
      env:
        GOOGLE_PROJECT: ${{ inputs.GOOGLE_PROJECT }}
        CR_URL: ${{ inputs.CR_URL }}
