name: Deploy Cloud Run to Dev Environment
on:
  workflow_call:

jobs:
    push_to_artifact:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: 'actions/checkout@v4'

            - name: Config GCP Auth
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: ${{ secrets.GCP_CREDENTIALS }}

            - name: Prepare GCP Auth to GCP Artifactory
              run: |
                gcloud auth configure-docker ${{ env.CR_URL }}

            - name: 'Set up GCP Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v0'
              with:
                project_id: ${{ env.GOOGLE_PROJECT }}
                export_default_credentials: true

            - name: Build and Push Container Image to GCP Artifactory
              env:
                GOOGLE_PROJECT: ${{ env.GOOGLE_PROJECT }}
              run: | 
                docker build -t ${{ env.CR_URL }}/${{ env.GOOGLE_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }} . 
                docker push ${{ env.CR_URL }}/${{ env.GOOGLE_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }}

            - id: 'Deploy the image to Cloud Run'
              uses: 'google-github-actions/deploy-cloudrun@v2'
              env:
                GOOGLE_PROJECT: ${{ env.GOOGLE_PROJECT }}
              with:
                SERVICE: '${{ env.SERVICE }}'
                region: '${{ env.REGION }}'
                image: ${{ env.CR_URL }}/${{ env.GOOGLE_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }}